### ISSUE TITLE
Not for ff2?

### ISSUE THREAD

**Issue by MCCoy0513** [hmsjayne/ffr-hmsj#55]
Final fantasy dawn of souls is for final fantasy 1 AND 2 not just one you know, that's my issue I have not everything has to be for ff1

**Comment by stellamazeika** [comment]
We are well aware of the base game this project is built upon, however we as developers are much more familiar with FF1 as both a vanilla game and as a randomizer.

As such, the interest and expertise of the development team is currently centered around FF1. While I understand your disappointment, this issue tracker is for issues with the code or for constructive suggestions, not for random demands and lamentations.

If you wish to see an FF2 randomizer in the world, I invite you to fork the repo.
